export const getSettingsStyles = (COLORS, user) => ({
  mainContainer: { flex: 1, backgroundColor: COLORS.background },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 64,
    paddingBottom: 20,
    paddingHorizontal: 24,
    borderBottomWidth: 1,
    backgroundColor: COLORS.surfaceElevated,
    borderBottomColor: COLORS.border,
  },
  backButton: { padding: 6 },
  headerTitle: { fontSize: 18, fontWeight: 'bold', color: COLORS.textPrimary },
  headerSpacer: { width: 36 },
  contentContainer: { paddingHorizontal: 24, paddingTop: 16 },
  notificationToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 18,
    borderBottomWidth: user?.notifications_enabled !== 0 ? 0 : 1,
    borderBottomColor: COLORS.border,
  },
  settingLabelRow: { flexDirection: 'row', alignItems: 'center' },
  settingLabel: { fontSize: 16, fontWeight: '500', marginLeft: 16, color: COLORS.textPrimary },
  intervalSection: { paddingBottom: 18, borderBottomWidth: 1, borderBottomColor: COLORS.border },
  intervalTitle: { fontSize: 14, fontWeight: '600', marginBottom: 12, color: COLORS.textSecondary },
  intervalOptionsRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 8 },
  intervalOption: (isSelected) => ({
    flex: 1,
    paddingVertical: 10,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 1,
    backgroundColor: isSelected ? COLORS.primary : 'transparent',
    borderColor: isSelected ? COLORS.primary : COLORS.border,
  }),
  intervalOptionText: (isSelected) => ({
    fontSize: 13,
    fontWeight: '600',
    color: isSelected ? '#fff' : COLORS.textPrimary,
  }),
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 18,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  actionText: { fontSize: 16, fontWeight: '500', marginLeft: 16, color: COLORS.textPrimary },
  logoutText: { fontSize: 16, fontWeight: '500', marginLeft: 16, color: COLORS.error },
});
