export const styles = {
  container: "bg-light-surfaceElevated dark:bg-dark-surfaceElevated rounded-2xl p-5 mb-5 border border-light-border dark:border-dark-border shadow-sm",
  title: "text-lg font-bold text-text-lightPrimary dark:text-text-darkPrimary mb-4",
  searchContainer: "flex-row gap-2.5 mb-4",
  searchInput: "flex-1 bg-light-bg dark:bg-dark-bg border border-light-border dark:border-dark-border text-text-lightPrimary dark:text-text-darkPrimary rounded-xl px-4 py-3 h-12 text-sm",
  searchButton: "w-12 h-12 bg-light-bg dark:bg-dark-bg border border-light-border dark:border-dark-border rounded-xl justify-center items-center",
  searchButtonText: "text-base",
  userRow: "flex-row items-center p-3 rounded-xl mb-2 border",
  userRowSelected: "bg-brand-primary/10 border-brand-primary/30",
  userRowUnselected: "bg-light-bg dark:bg-dark-bg border-light-border dark:border-dark-border",
  avatarContainer: "w-10 h-10 rounded-full bg-brand-primary justify-center items-center mr-3",
  avatarText: "text-white font-bold text-[15px]",
  userInfoContainer: "flex-1",
  usernameText: "text-[15px] font-bold text-text-lightPrimary dark:text-text-darkPrimary",
  emailText: "text-xs text-text-lightSecondary dark:text-text-darkSecondary mt-0.5",
  adminBadge: "bg-status-error px-2 py-0.5 rounded text-white text-[10px] font-bold ml-2",
  privilegesBox: "mt-4 p-4 bg-light-bg dark:bg-dark-bg rounded-xl border border-light-border dark:border-dark-border",
  privilegesHeader: "text-[15px] font-bold text-text-lightPrimary dark:text-text-darkPrimary mb-3 pb-3 border-b border-light-border dark:border-dark-border",
  privilegeRow: "flex-row items-center py-2.5",
  checkboxContainer: "w-5 h-5 rounded-[5px] border justify-center items-center mr-3",
  checkboxChecked: "bg-brand-primary border-brand-primary",
  checkboxUnchecked: "bg-light-surfaceElevated dark:bg-dark-surfaceElevated border-light-border dark:border-dark-border",
  checkmark: "text-white text-xs font-bold leading-[14px]",
  privilegeLabel: "text-[13px] text-text-lightPrimary dark:text-text-darkPrimary flex-1",
  saveButtonContainer: "mt-4 rounded-xl overflow-hidden shadow-sm",
  saveButtonGradient: "py-3 items-center justify-center",
  saveButtonText: "text-white text-[15px] font-bold"
};
