export const styles = {
  overlay: "flex-1 bg-black/60 justify-center p-5",
  modalContainer: "bg-light-surfaceElevated dark:bg-dark-surfaceElevated rounded-2xl p-5 max-h-[90%]",
  header: "flex-row justify-between items-center mb-4",
  title: "text-lg font-bold text-text-lightPrimary dark:text-text-darkPrimary",
  closeButton: "p-1",
  tagsContainer: "flex-row flex-wrap gap-2 justify-center",
  tagButton: "flex-row items-center px-3 py-2.5 rounded-full border gap-1.5",
  tagText: "font-semibold",
  loadingIndicator: "my-5",
  recommendationsTitle: "text-text-lightSecondary dark:text-text-darkSecondary mb-3",
  recommendationCard: "flex-row bg-light-bg dark:bg-dark-bg rounded-xl p-2.5 mb-2.5 border border-light-border dark:border-dark-border",
  iconContainer: "w-15 h-20 bg-light-surfaceElevated dark:bg-dark-surfaceElevated rounded-lg justify-center items-center mr-3",
  recommendationContent: "flex-1 justify-center",
  recommendationTitle: "text-base font-bold text-text-lightPrimary dark:text-text-darkPrimary",
  recommendationAuthor: "text-[13px] text-text-lightMuted dark:text-text-darkMuted mt-1",
  typeBadgeContainer: "self-start mt-2 px-2 py-1 rounded-lg",
  typeBadgeText: "text-[10px] font-semibold text-brand-primary",
  emptyText: "text-text-lightMuted dark:text-text-darkMuted text-center my-5",
  backButton: "mt-3 p-3 items-center border border-light-border dark:border-dark-border rounded-lg",
  backButtonText: "text-text-lightSecondary dark:text-text-darkSecondary",
  doNotShowContainer: "flex-row items-center mt-5",
  doNotShowText: "ml-2 text-text-lightSecondary dark:text-text-darkSecondary"
};
