export const EMOTION_TAGS = [
  { id: 'mutluluk', label: 'Mutluluk', iconName: 'Smiley' },
  { id: 'heyecan', label: 'Heyecan', iconName: 'Lightning' },
  { id: 'yalnizlik', label: 'Yalnızlık', iconName: 'UserMinus' },
  { id: 'uzuntu', label: 'Üzüntü', iconName: 'CloudRain' },
  { id: 'korku', label: 'Korku', iconName: 'Ghost' },
  { id: 'ofke', label: 'Öfke', iconName: 'Flame' },
  { id: 'saskinlik', label: 'Şaşkınlık', iconName: 'WarningCircle' },
  { id: 'tiksinme', label: 'Tiksinme', iconName: 'HandPalm' },
  { id: 'huzur', label: 'Huzur', iconName: 'Plant' },
  { id: 'minnettarlik', label: 'Minnettarlık', iconName: 'HandsClapping' },
  { id: 'sevgi', label: 'Sevgi', iconName: 'Heart' },
  { id: 'sefkat', label: 'Şefkat', iconName: 'Heartbeat' },
  { id: 'umut', label: 'Umut', iconName: 'Sparkle' },
  { id: 'merak', label: 'Merak', iconName: 'MagnifyingGlass' },
  { id: 'ilham', label: 'İlham', iconName: 'Lightbulb' },
  { id: 'kaygi', label: 'Kaygı', iconName: 'Wind' },
  { id: 'pismanlik', label: 'Pişmanlık', iconName: 'ArrowUUpLeft' },
  { id: 'bikkinlik', label: 'Bıkkınlık', iconName: 'BatteryEmpty' },
  { id: 'umutsuzluk', label: 'Umutsuzluk', iconName: 'CloudSlash' },
  { id: 'nostalji', label: 'Nostalji', iconName: 'ClockCounterClockwise' },
  { id: 'melankoli', label: 'Melankoli', iconName: 'Cloud' },
  { id: 'ozlem', label: 'Özlem', iconName: 'PaperPlaneTilt' },
  { id: 'aitlik', label: 'Aitlik', iconName: 'Users' },
  { id: 'yabancilasma', label: 'Yabancılaşma', iconName: 'Alien' },
  { id: 'tukenmislik', label: 'Tükenmişlik', iconName: 'BatteryWarning' },
  { id: 'hissizlik', label: 'Hissizlik', iconName: 'Snowflake' },
  { id: 'kafa_karisikligi', label: 'Kafa Karışıklığı', iconName: 'Question' },
  { id: 'mahcubiyet', label: 'Mahcubiyet', iconName: 'EyeClosed' },
  { id: 'guvende_hissetme', label: 'Güvende Hissetme', iconName: 'ShieldCheck' },
  { id: 'suphe', label: 'Şüphe', iconName: 'MagnifyingGlassPlus' },
  { id: 'tedirginlik', label: 'Tedirginlik', iconName: 'Warning' },
];

export const CONTENT_TYPES = {
  movie: { label: 'Film', iconName: 'FilmStrip', type: 'movie' },
  series: { label: 'Dizi', iconName: 'Television', type: 'series' },
  book: { label: 'Kitap', iconName: 'Books', type: 'book' },
};
