export const EMOTION_TAGS = [
  { id: 'mutluluk', label: 'Mutluluk', iconName: 'Smiley', color: '#F59E0B' },
  { id: 'heyecan', label: 'Heyecan', iconName: 'Lightning', color: '#3B82F6' },
  { id: 'yalnizlik', label: 'Yalnızlık', iconName: 'UserMinus', color: '#64748B' },
  { id: 'uzuntu', label: 'Üzüntü', iconName: 'CloudRain', color: '#2563EB' },
  { id: 'korku', label: 'Korku', iconName: 'Ghost', color: '#7C3AED' },
  { id: 'ofke', label: 'Öfke', iconName: 'Flame', color: '#EF4444' },
  { id: 'saskinlik', label: 'Şaşkınlık', iconName: 'WarningCircle', color: '#F97316' },
  { id: 'tiksinme', label: 'Tiksinme', iconName: 'HandPalm', color: '#65A30D' },
  { id: 'huzur', label: 'Huzur', iconName: 'Plant', color: '#10B981' },
  { id: 'minnettarlik', label: 'Minnettarlık', iconName: 'HandsClapping', color: '#EC4899' },
  { id: 'sevgi', label: 'Sevgi', iconName: 'Heart', color: '#F43F5E' },
  { id: 'sefkat', label: 'Şefkat', iconName: 'Heartbeat', color: '#FB7185' },
  { id: 'umut', label: 'Umut', iconName: 'Sparkle', color: '#06B6D4' },
  { id: 'merak', label: 'Merak', iconName: 'MagnifyingGlass', color: '#6366F1' },
  { id: 'ilham', label: 'İlham', iconName: 'Lightbulb', color: '#EAB308' },
  { id: 'kaygi', label: 'Kaygı', iconName: 'Wind', color: '#D97706' },
  { id: 'pismanlik', label: 'Pişmanlık', iconName: 'ArrowUUpLeft', color: '#8B5CF6' },
  { id: 'bikkinlik', label: 'Bıkkınlık', iconName: 'BatteryEmpty', color: '#475569' },
  { id: 'umutsuzluk', label: 'Umutsuzluk', iconName: 'CloudSlash', color: '#334155' },
  { id: 'nostalji', label: 'Nostalji', iconName: 'ClockCounterClockwise', color: '#B45309' },
  { id: 'melankoli', label: 'Melankoli', iconName: 'Cloud', color: '#60A5FA' },
  { id: 'ozlem', label: 'Özlem', iconName: 'PaperPlaneTilt', color: '#D946EF' },
  { id: 'aitlik', label: 'Aitlik', iconName: 'Users', color: '#F97316' },
  { id: 'yabancilasma', label: 'Yabancılaşma', iconName: 'Alien', color: '#14B8A6' },
  { id: 'tukenmislik', label: 'Tükenmişlik', iconName: 'BatteryWarning', color: '#991B1B' },
  { id: 'hissizlik', label: 'Hissizlik', iconName: 'Snowflake', color: '#94A3B8' },
  { id: 'kafa_karisikligi', label: 'Kafa Karışıklığı', iconName: 'Question', color: '#A855F7' },
  { id: 'mahcubiyet', label: 'Mahcubiyet', iconName: 'EyeClosed', color: '#FB923C' },
  { id: 'guvende_hissetme', label: 'Güvende Hissetme', iconName: 'ShieldCheck', color: '#22C55E' },
  { id: 'suphe', label: 'Şüphe', iconName: 'MagnifyingGlassPlus', color: '#4F46E5' },
  { id: 'tedirginlik', label: 'Tedirginlik', iconName: 'Warning', color: '#F59E0B' },
];

export const CONTENT_TYPES = {
  movie: { label: 'Film', iconName: 'FilmStrip', type: 'movie' },
  series: { label: 'Dizi', iconName: 'Television', type: 'series' },
  book: { label: 'Kitap', iconName: 'Books', type: 'book' },
};
